export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const START_PURCHASING = 'START_PURCHASING';
export const SUCCESS_PURCHASING = 'SUCCESS_PURCHASING';
export const FAILURE_PURCHASING = 'FAILURE_PURCHASING';
export const INITIALIZE_PURCHASE = 'INITIALIZE_PURCHASE';